#cloud-config
users:
  - name: Student
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFTpBJNPuYjaDheQjVLVZas37Q9tyKuoT9YcN+SvTxc5 student@DESKTOP-1NUD89T
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
packages:
  - wget
  - ntpdate