---
- name: Installeer NGINX via shell #aanpassing
  hosts: all
  become: yes
  tasks:
    - name: Installeer NGINX zonder apt module
      shell: "apt-get update && apt-get install -y nginx"
      register: nginx_install
      changed_when: "'is already the newest version' not in nginx_install.stdout"
      failed_when: nginx_install.rc != 0
