name: derraform destroy alleen handmatig

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: terraform init
        run: terraform init

      - name: terraform destroy
        run: terraform destroy -auto-approve
