name: terraform Deploy

on:
  push:
    branches:
      - main
    paths:
      - '*.tf'
      - inventory.ini

jobs:
  terraform-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: terraform init
        run: terraform init

#      - name: terraform format checken
#        run: terraform fmt -check

      - name: terraform valideren
        run: terraform validate

      - name: terraform plan
        run: terraform plan

      - name: terraform apply
        run: terraform apply -auto-approve
